In [9]:
# Ödev-1 Sayılardan oluşan bir boyutlu array oluşturulur.
# Arrayi oluştururken sayıların veri tipini integer olarak belirtilir.
# Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [12]:
import numpy as np
number_array =np.array([12,7.8,34,9.2,56,3.14],dtype="int")

print(number_array.ndim)
print(number_array.size)

1
6


In [ ]:
# Ödev-2 İki ve üç boyutlu arrayler oluşturulur.
# Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.
# Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [34]:
array_2d = np.array([[1,3,5],[7,9,11]])

array_3d = np.array([[[0,2,4],[6,8,10]],
                    [[12,14,16],[18,20,22]]])

print("the dimension of array_2d :",array_2d.ndim)

print("the dimension of array_3d :",array_3d.ndim)

print("number of elements of array_2d :",array_2d.size)

print("number of elements of array_3d :",array_3d.size)

print("Row and column information in array_2d :",np.shape(array_2d))

print("Row and column information in array_3d :",np.shape(array_3d))


the dimension of array_2d : 2
the dimension of array_3d : 3
number of elements of array_2d : 6
number of elements of array_3d : 12
Row and column information in array_2d : (2, 3)
Row and column information in array_3d : (2, 2, 3)


In [24]:
array_2d = np.array([[1,3,5],[7,9,11]])

array_3d = np.array([[[0,2,4],[6,8,10]],
                    [[12,14,16],[18,20,22]]])

In [31]:
print(array_2d[1,2])
print(array_2d[0,1])

print(array_3d[1,0,1])
print(array_3d[0,1,1])

11
3
14
8


In [ ]:
array_2d = np.array([[1,3,5],[7,9,11]])

array_3d = np.array([[[0,2,4],[6,8,10]],
                    [[12,14,16],[18,20,22]]])

In [33]:
print(array_2d[0, :])  
print(array_2d[:, 1]) 
print(array_2d[1:, 1:]) 
print(" ")
print(array_3d[0, :, :])  
print(array_3d[:, 0, :])  
print(array_3d[1, 1, :]) 

[1 3 5]
[3 9]
[[ 9 11]]
 
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  2  4]
 [12 14 16]]
[18 20 22]


In [ ]:
# Ödev-3 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. 
# Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 

In [36]:
import numpy as np

d1_array =np.array ([2,4,6,8])
print("array of one dimension :",d1_array)
print(" ")

d2_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("array of two dimension :",d2_array)
print(" ")

d3_array = np.array ([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]]])
print("array of three dimension :",d3_array)


array of one dimension : [2 4 6 8]
 
array of two dimension : [[1 2 3]
 [4 5 6]
 [7 8 9]]
 
array of three dimension : [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [37]:
d1_array =np.array ([2,4,6,8])

print(d1_array[0])
print(d1_array[3])

print(" ")

print(d1_array[0:])
print(d1_array[1:4])

2
8
 
[2 4 6 8]
[4 6 8]


In [38]:
d2_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(d2_array[0,2])
print(d2_array[2,2])
print(d2_array[1,2])
print(" ")
print(d2_array[0:2,1:2])
print(d2_array[::2, ::2])

3
9
6
 
[[2]
 [5]]
[[1 3]
 [7 9]]


In [43]:
d3_array = np.array ([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]]])

print(d3_array[0,2,1])
print(d3_array[0,1,1])
print(d3_array[0,2,0])
print(" ")
print(d3_array[0, 1:3, 0:2])
print(d3_array[0, :, :])

8
5
7
 
[[4 5]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Ödev-4 Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [55]:
zeros_array = np.zeros((2,3),dtype="int")
ones_array = np.ones((2,3),dtype="int")

zeros_array

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
ones_array

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
row_concatenate = np.concatenate((zeros_array, ones_array), axis=0)
column_concatenate =np.concatenate((zeros_array, ones_array), axis=1)

print("the concatenate of rows:",row_concatenate)
print(" ")
print("the concatenate of columns:",column_concatenate)

the concatenate of rows: [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
 
the concatenate of columns: [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
